version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=heart_of_news_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=heart_of_news_test
      - PROJECT_NAME=Heart of News Test
      - SECRET_KEY=testsecretkey
      - CORS_ORIGINS=http://localhost:3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - STORAGE_BUCKET_NAME=heart-of-news-media-test
      - SCRAPER_USER_AGENT=HeartOfNewsBot-Test/1.0
      - SCRAPER_REQUEST_DELAY=0.1
    volumes:
      - .:/app
    command: >
      bash -c "
        pytest --cov=app tests/
      "