global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alerts@heartofnews.example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'slack-critical'
    continue: true
  - match:
      severity: warning
    receiver: 'slack-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'team@heartofnews.example.com'
    send_resolved: true

- name: 'slack-notifications'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/REPLACE_WITH_WEBHOOK_URL'
    channel: '#monitoring'
    send_resolved: true
    title: '{{ .GroupLabels.alertname }}'
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Description:* {{ .Annotations.description }}
        *Severity:* {{ .Labels.severity }}
        *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ end }}

- name: 'slack-critical'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/REPLACE_WITH_WEBHOOK_URL'
    channel: '#alerts-critical'
    send_resolved: true
    title: '🚨 CRITICAL ALERT: {{ .GroupLabels.alertname }}'
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Description:* {{ .Annotations.description }}
        *Severity:* {{ .Labels.severity }}
        *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']