"""Initial migration

Revision ID: d7f45a790b0f
Revises: 
Create Date: 2025-06-25 23:53:54.056950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f45a790b0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('feed_url', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategories', sa.JSON(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('bias_score', sa.Float(), nullable=True),
    sa.Column('sensationalism_score', sa.Float(), nullable=True),
    sa.Column('scraper_config', sa.JSON(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('crawl_frequency', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_url'), 'sources', ['url'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('political_bias', sa.Float(), nullable=True),
    sa.Column('emotional_language', sa.Float(), nullable=True),
    sa.Column('fact_opinion_ratio', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_original_url'), 'articles', ['original_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_original_url'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_sources_url'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###