apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: heart-of-news
    component: celery-worker
spec:
  replicas: 1  # Will be overridden by environment overlays
  selector:
    matchLabels:
      app: heart-of-news
      component: celery-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: heart-of-news
        component: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: heartofnews/backend:latest  # Will be overridden by kustomize
        imagePullPolicy: Always
        command: ["celery", "-A", "app.worker", "worker", "--loglevel=info", "--concurrency=4"]
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # All other environment variables will be supplied by ConfigMap and Secrets
        envFrom:
        - configMapRef:
            name: api-config
        - secretRef:
            name: api-secrets
        livenessProbe:
          exec:
            command:
            - celery
            - -A
            - app.worker
            - inspect
            - ping
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000