apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  labels:
    app: heart-of-news
    component: scraper
spec:
  replicas: 1  # Will be overridden by environment overlays
  selector:
    matchLabels:
      app: heart-of-news
      component: scraper
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: heart-of-news
        component: scraper
    spec:
      containers:
      - name: scraper
        image: heartofnews/backend:latest  # Will be overridden by kustomize
        imagePullPolicy: Always
        command: ["python", "-m", "app.scraper.main"]
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # All other environment variables will be supplied by ConfigMap and Secrets
        envFrom:
        - configMapRef:
            name: api-config
        - secretRef:
            name: api-secrets
        livenessProbe:
          httpGet:
            path: /api/v1/health/scraper
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000