apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: heart-of-news-production

resources:
  - ../../base
  - pdb.yaml  # Pod Disruption Budget
  - monitoring-config.yaml

patchesStrategicMerge:
  - patches/api-deployment-patch.yaml
  - patches/celery-worker-deployment-patch.yaml
  - patches/ingress-patch.yaml

commonLabels:
  environment: production

# Production-specific resources
configMapGenerator:
  - name: api-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - DB_POOL_SIZE=20
      - DB_MAX_OVERFLOW=30
      - DB_POOL_RECYCLE=1800
      - CACHE_TTL_SHORT=60
      - CACHE_TTL_MEDIUM=300
      - CACHE_TTL_LONG=3600
      - CACHE_TTL_VERY_LONG=86400
      - SECURITY_CONTENT_SECURITY_POLICY="default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https:;"

secretGenerator:
  - name: api-secrets
    envs:
      - secrets/.env.production

# Use a specific image for production
images:
  - name: heartofnews/backend
    newName: heartofnews/backend
    newTag: production-latest  # Will be replaced by CI/CD